### ISSUE TITLE
DBGraph.fasta not generated

### ISSUE THREAD

**Issue by Arkhaan** [jfostier/brownie#18]
Hi,
When running brownie with the following command :
brownie graphConstruction -k 71 -t 12 -o DBGraph.fasta reads.fastq

The software stops at stage 4 and does not enter stage 5, thus not giving the correct output. Or is it something I missed?

Edit : I found in the code that with the graphConstruction command, the stage 5 is skipped. Is this the intended behavior?

**Comment by Arkhaan** [comment]
On a related note, removing the graphConstruction command on the line above allows to enter stage 5, however brownie crashes with a Segmentation fault.
It happens at this moment :
**From log**
Creating graph... done (1min 7s)
Graph contains 16416137 nodes and 45580292 arcs
Creating kmer lookup table... done (23min 34s)
Building suffix array (sparseness factor: 1)...
**From error**
bash: line 1: 38740 Segmentation fault      (core dumped) brownie -k 31 -t 12 -o DBGraph.fasta files.fastq

**Comment by gmiclotte** [comment]
Hello,

If you want the DBGraph.fasta file, i.e. the corrected de Bruijn graph in fasta format, then run
`brownie graphConstruction -k 71 -t 12 reads.fastq`
The `-o` option is used to specify the corrected reads output file.

Correcting reads happens in stage 5, if you just want the corrected de Bruijn graph, then you only need stages 1-4.

If brownie crashes while building the suffix array in stage 5, then try running with a higher sparseness factor (specified with option `-e` or `--essa`, default is 1, try `-e 2` or higher).

Kind regards,
Giles

**Comment by Arkhaan** [comment]
Thank you, it looks like I misinterpreted how to use it!
I am running it again, with correct parameters this time.
