### ISSUE TITLE
compile on RHEL 6

### ISSUE THREAD

**Issue by fretn** [jfostier/brownie#2]
Which gcc version is needed to compile this project ?

The RHEL 6 included gcc is not able to parse the -std=c++11 and -static-libstdc++ flags

**Comment by mahdiheydari** [comment]
Mine is: gcc version 4.8.3 20140911 (Red Hat 4.8.3-7) (GCC)

**Comment by gmiclotte** [comment]
If you use GCC 4.7 or a more recent version, this should fix the problem.

Kind regards,
Giles Miclotte

**Comment by fretn** [comment]
thanks for the info, it didn't work with gcc 4.8.0 I thought, but cmake was just ignoring it :)
