### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by SimonHegele** [jfostier/brownie#23]
Hello, me again.

I also tried installing brownie separately but this did not work either. I have downloaded the latest release, unpacked it and then proceeded as described for the installation.

`/root/brownie-1.0/src/coverage.cpp: In member function ‘void DBGraph::extractStatistic(int)’:`
`/root/brownie-1.0/src/coverage.cpp:183:35: error: ‘sqrt’ was not declared in this scope`
`  183 |                 StandardErrorMean=sqrt( sumOfSTD/num);`
`      |                                   ^~~~`
`make[2]: *** [src/CMakeFiles/brownie.dir/build.make:135: src/CMakeFiles/brownie.dir/coverage.cpp.o] Error 1`
`make[1]: *** [CMakeFiles/Makefile2:174: src/CMakeFiles/brownie.dir/all] Error 2`
`make: *** [Makefile:139: all] Error 2`
[stderr.txt](https://github.com/user-attachments/files/18095306/stderr.txt)
[stdout.txt](https://github.com/user-attachments/files/18095307/stdout.txt)

**Comment by gmiclotte** [comment]
Dear Simon


It seems your compiler is having trouble finding the std::sqrt function from the cmath library. Unfortunately, I haven’t been able to reproduce this issue on my end.

Could you try replacing the root CMakeLists.txt file with this one: [CMakeLists.txt](https://github.com/user-attachments/files/18097873/CMakeLists.txt)?

After replacing the file, please:

1. Completely remove the build folder.
2. Run the build commands again from scratch.

If this doesn’t resolve the issue, I’m not sure what else might be causing the problem. Knowing which compiler and version you’re using could provide a clue to the solution.


Kind regards
Giles Miclotte

**Comment by SimonHegele** [comment]
Dear Giles,

first time I tired it I used the released package. I have tried again, this time by cloning the repository and the installation was succesfull this time.
The issue was probably related to the compiler issue (I was using gcc 13.2.0).

Thank you very much for your support.
